add mask to loss
piercus/mmclassification pull request #1
Opened 2022-10-07 10:03 UTC by marouaneamz

this pull request adds option of the mask to the loss which allows not to take  into account  images in the loss if they do not have labels for certain task

2022-10-11 14:05 UTC, piercus requested changes
@marouaneamz please see inline comments

2022-10-11 14:05 UTC, piercus commented on mmcls/datasets/pipelines/formatting.py
> +        results['gt_label'] = dict(label=gt_label,mask=gt_mask)
```suggestion
                gt_label[task] = dict(label=to_tensor(results[label_key]), mask=results[mask_key])


        results['gt_label'] = gt_label
```

2022-10-11 14:05 UTC, piercus commented on mmcls/models/heads/multi_task_head.py
> +            mask = gt_label['mask'][task_name]
```suggestion
            task_gt_label = gt_label[task_name]
            if type(task_gt_label) is dict :
              mask = task_gt_label['mask']
              label = task_gt_label['label']
            else: # a tensor
              label = task_gt_label['label']
              batch_n = label.shape[0]
              mask = to_tensor([True]*batch_n)
```

2022-10-12 14:47 UTC, marouaneamz commented
I try to adapt the pipeline if there is no mask , but I can't do your method because we add the labels with the first if (if we haven't hardcoded the tasks [here](https://github.com/piercus/mmclassification/blob/multi-task/mmcls/datasets/pipelines/formatting.py#L52) ), and in this block we add the labels and the maks we go through the whole results list and not all of them at once

2022-10-18 11:43 UTC, piercus approved these changes

2022-10-18 11:43 UTC, piercus commented on mmcls/datasets/pipelines/formatting.py
> +                    gt_mask[task] = v
```suggestion
            for k, v in results.items():
                if k.endswith('_img_label'):
                    task = k[:-10]
                    if task not in gt_label:
                      gt_label[task] = dict()
                    gt_label[task]['label'] = to_tensor(v)
                elif k.endswith('_mask'):
                    task = k[:-5]
                    if task not in gt_label:
                      gt_label[task] = dict()
                    gt_label[task]['mask'] = v
```

2022-10-18 11:43 UTC, merged