Multi task mzr
piercus/mmclassification pull request #7
Opened 2022-12-02 15:58 UTC by marouaneamz

2022-12-05 09:54 UTC, piercus requested changes

2022-12-05 09:54 UTC, piercus commented on mmcls/evaluation/metrics/multi_task.py
> +                metric.process(data_batch, filtered_data_samples)
Please mask the data_batch here

2022-12-05 09:54 UTC, piercus commented on tests/test_evaluation/test_metrics/test_multi_task_metrics.py
> +    print(pred2)
remove

2022-12-05 09:54 UTC, piercus commented on tests/test_structures/test_datasample.py
> -        self.assertEqual(getattr(label, 'task0'), 0)
Please create a little test at least to cover the MultiTaskDataSample init

2022-12-05 11:49 UTC, piercus approved these changes

2022-12-05 11:50 UTC, piercus commented
FAILED tests/test_evaluation/test_metrics/test_multi_task_metrics.py::MultiTaskMetric::test_evaluate - TypeError: list indices must be integers or slices, not str

2022-12-05 14:03 UTC, marouaneamz commented on mmcls/models/heads/multi_task_head.py
> +                task_samples = [item.get(task_name) for item in data_samples]
if the task does not exist, it will return None , and it is impossible to do set_pred for Nones

2022-12-05 14:05 UTC, marouaneamz commented on mmcls/models/heads/multi_task_head.py
> +                task_samples = [item.get(task_name) for item in data_samples]
```
File "tools/train.py", line 164, in <module>
    main()
  File "tools/train.py", line 160, in main
    runner.train()
  File "/home/marouane/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1659, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/marouane/.local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 94, in run
    self.runner.val_loop.run()
  File "/home/marouane/.local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 343, in run
    self.run_iter(idx, data_batch)
  File "/home/marouane/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/marouane/.local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 363, in run_iter
    outputs = self.runner.model.val_step(data_batch)
  File "/home/marouane/.local/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 133, in val_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/marouane/.local/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 301, in _run_forward
    results = self(**data, mode=mode)
  File "/home/marouane/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/marouane/dev/mmclassification1.x/mmcls/models/classifiers/image.py", line 119, in forward
    return self.predict(inputs, data_samples)
  File "/home/marouane/dev/mmclassification1.x/mmcls/models/classifiers/image.py", line 244, in predict
    return self.head.predict(feats, data_samples, **kwargs)
  File "/home/marouane/dev/mmclassification1.x/mmcls/models/heads/multi_task_head.py", line 124, in predict
    task_samples = head.predict(feats, task_samples)
  File "/home/marouane/dev/mmclassification1.x/mmcls/models/heads/cls_head.py", line 130, in predict
    predictions = self._get_predictions(cls_score, data_samples)
  File "/home/marouane/dev/mmclassification1.x/mmcls/models/heads/cls_head.py", line 144, in _get_predictions
    data_sample.set_pred_score(score).set_pred_label(label)
AttributeError: 'NoneType' object has no attribute 'set_pred_score'

```

2022-12-06 13:43 UTC, piercus requested changes

2022-12-06 13:43 UTC, piercus commented on mmcls/models/heads/cls_head.py
> +            out_data_samples.append(data_sample_)
```suggestion
            if data_sample is None:
                data_sample = ClsDataSample()

            data_sample.set_pred_score(score).set_pred_label(label)
            out_data_samples.append(data_sample)
```

2022-12-06 14:37 UTC, merged